server:
  port: 8080

spring:
  application:
    name: myhospital-gateway
    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.port}
      

zuul:
  prefix: /api
  routes:
    appointment:
      path: /appointment/**
      serviceId: appointment-service
      stripPrefix: false
    patient:
      path: /patient/**
      serviceId: patient-service
      stripPrefix: false
      
endpoints:
  routes:
    enabled: true